# Cloud Build configuration for bxspace-api
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'
    id: 'build-image'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}'
    id: 'push-image'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=gcp'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      - '--set-env-vars=GCS_BUCKET_PREFIX=${_GCS_BUCKET_PREFIX}'
      - '--set-env-vars=GCS_LOCATION=${_GCS_LOCATION}'
      - '--set-env-vars=ENVIRONMENT=production'
    id: 'deploy-cloud-run'

# Substitution variables with defaults
substitutions:
  _SERVICE_NAME: 'bxspace-api'
  _REGION: 'us-central1'
  _REPOSITORY: 'docker-repo'
  _MEMORY: '512Mi'
  _CPU: '1'
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '0'
  # GCS Configuration
  _GCS_BUCKET_PREFIX: 'bxspace-prod'
  _GCS_LOCATION: 'US'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
